export const PAYMENT_EVENT_REPOSITORY = Symbol('PAYMENT_EVENT_REPOSITORY');
export const PAYMENT_JOB_QUEUE = Symbol('PAYMENT_JOB_QUEUE');
export const MERCADOPAGO_WEBHOOK_SECRET = Symbol('MERCADOPAGO_WEBHOOK_SECRET');
